"""add monthly interest rate to credit applications

Guarda la tasa mensual con la que se liquido cada cuota. La columna se agrega NOT NULL y sin
valor por defecto: la tabla se creo en la revision anterior y no existe todavia ningun dato
desplegado, asi que no hay filas a las que habria que inventarles una tasa.

Revision ID: d4e404922d13
Revises: c6126b61bbc2
Create Date: 2026-08-14 12:06:05.323835

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d4e404922d13"
down_revision: str | Sequence[str] | None = "c6126b61bbc2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "credit_applications",
        sa.Column("monthly_interest_rate", sa.Numeric(precision=8, scale=6), nullable=False),
    )
    op.create_check_constraint(
        op.f("ck_credit_applications_monthly_interest_rate_non_negative"),
        "credit_applications",
        "monthly_interest_rate >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_credit_applications_monthly_interest_rate_non_negative"),
        "credit_applications",
        type_="check",
    )
    op.drop_column("credit_applications", "monthly_interest_rate")
    # ### end Alembic commands ###
